#!/bin/bash
# Wrapper script for launchd to inherit shell environment
# Generated by mcp-cloudflare-kit

# Source environment variables

[ -f ~/.zshenv ] && source ~/.zshenv

[ -f ~/.zapi_keys ] && source ~/.zapi_keys


# Change to project directory
cd /Users/ianuser/repos/other/para/para-mcp

# Set server mode
export USE_HTTP=true
export PORT=8000

# Run the MCP server
exec venv/bin/python -m src.server